language: cpp

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libgl1-mesa-dev libx11-dev libsndfile1-dev libsamplerate0-dev libjack-jackd2-dev

script: make

deploy:
  provider: releases
  api_key: "c17fceb442782073af17a8865e61a11ba10d1ea0"
  file_glob: true
  file: "bin/ninjas*"
  skip_cleanup: true
  on:
    tags: true
    
