language: cpp

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libgl1-mesa-dev libx11-dev libsndfile1-dev libsamplerate0-dev libjack-jackd2-dev

script:
- make
- ./create_release_tarball.sh

deploy:
  provider: releases
  api_key:
    secure: lOw3uWTRDoULOl+z1hOgcfgxxM3yFL2Ee22KkwGs6tEtIHlrFa3lIxH2lqdhkV5g7ZmoUJlmIfmNG3nLWCvJ8ZKQWowGDq5lAL5GCow+933FoZYoLuvLNwacudM8fNM/pu97jBxIw5JBnox2ep7vp5f/O0tQopjqFWwA5nccGmq4VU6QSacPPA6K0LXBi1N45ta1Qm4o3IcS6l8rxZzJGIEmRX7ldpGqy0oVGde89P9k2Gxo6/GAO49XJMVkemdmuZvrkMhq8WLAfJb6kTCu2AtMvh57nW/+GCuCZ8PaVEG2SN9ocamVm9SfMAllWbpb4a8gG53fPPiMXgZWG0O9iynUYBEJf7VB2d4PnNd17TQatrBEplNlXRUgRAhSJ++Haf5knhxT0RWUXMJhCO5Qk97TrmrBDMQ0DtVl21ESsF9RKfRQfnQU1F8fxpTCWtAJtKfRaim/W3By7qHzWNg7n9HYOBq2+leQ5F9CXBDEmhw1huG0IDKW/CIQBQWXtWICrsv4L57yQ27NckzCc48HTe8p95xwSP/xZIQ9yx6ePAo4PCJMU+DF9v17+Mj+8SVcz3AYNav7AEnfCf0wAiJA4Lcpou9CVzaegaF806PxNzXzCCJ57LB1uAlhiyMQ5SnVhLDM1qlg9RVQy6xmr1flXX1tno/P956Rs12CcKYMzKM=
  file: bin/ninjas.tar.gz
  skip_cleanup: true
  on:
    repo: rghvdberg/ninjas
    
